src/objects/Caliber_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Category</label>
        <referenceTo>Caliber_Category__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <label>Assessment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exam</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Points__c</fullName>
        <description>An arbitrary number designating the maximum number of points a trainee can earn for an assessment. The weighted score (out of 100%) is determined by Caliber_Grade__c.Score__c / Max_Points__c</description>
        <label>Max Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Id__c</fullName>
        <label>Training Id</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <description>The week that the test was administered, for example a Java Verbal test on Week 1.</description>
        <label>Week Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Caliber Assessment</label>
    <nameField>
        <displayFormat>ASMNT-{0000000}</displayFormat>
        <label>Caliber Assessment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Caliber_Note__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Caliber Notes</relationshipLabel>
        <relationshipName>Caliber_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_QC_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is Checked that indicates that this note is QC feedback.</description>
        <label>Is QC Feedback</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Note_Type__c</fullName>
        <label>Note Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trainee</fullName>
                </value>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>QC Trainee</fullName>
                </value>
                <value>
                    <fullName>QC Batch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QC_Status__c</fullName>
        <label>QC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Superstar</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Average</fullName>
                </value>
                <value>
                    <fullName>Poor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Caliber Notes</relationshipLabel>
        <relationshipName>Caliber_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <label>Week Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Caliber Note</label>
    <nameField>
        <displayFormat>Note-{0000000}</displayFormat>
        <label>Caliber Note Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrainingTrack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Track</label>
        <referenceTo>Training_Track__c</referenceTo>
        <relationshipLabel>Trainings</relationshipLabel>
        <relationshipName>Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QATestDataFactory.cls
@isTest
public class QATestDataFactory {
    public static void createTestData(String trainerId, Integer numAssociates, Integer numBatches){
        // Create associates
        List<Contact> associates = new List<Contact>();
        for(Integer i = 0; i < numAssociates; i++){
            Contact a = new Contact();
            a.Email = 'batch' + 'trainee' + i + '@test.com';
            a.Master_Stage__c = 'Training';
            a.FirstName = 'batch';
            a.LastName = 'trainee ' + i;
            associates.add(a);
        }
        insert associates;
        
        //create Training_Track
        Training_Track__c track = new Training_Track__c();
        track.Active__c = true;
        track.ShortName__c = 'Salesforce';
        track.Name = 'Salesforce';
        insert track; 
        
        Date startDate = Date.parse('09/03/2018');
        Date endDate = Date.parse('11/16/2018');
        
        List<Training__c> batches = new List<Training__c>();
        for(Integer i = 1; i <= numBatches; i++){
            Training__c batch = new Training__c();
            batch.StartDate__c = startDate.addDays(7*i);
            batch.EndDate__c = endDate.addDays(7*i);
            batch.Status__c = 'In Progress';
            batch.Trainer__c = trainerId;
            batch.TrainingTrack__c = track.Id;
            batches.add(batch);
        }
        
        insert batches;
        
        //Create Training Assignments
        List<Training_Assignment__c> taList = new List<Training_Assignment__c>();
        for(Training__c batch : batches){
            for(Integer i = 0; i < numAssociates; i++){
                Training_Assignment__c ta = new Training_Assignment__c();
                ta.Contact__c = associates[i].Id;
                ta.Training__c = batch.Id;
                ta.Name = 'TA-' + i;
                taList.add(ta);
            }
        }
        insert taList;
        
        //create categories for assessments
        List<Caliber_Category__c> cats = new List<Caliber_Category__c>();
        List<String> catNames = new List<String>{'SF Security', 'SF Data Model', 'Sales Cloud', 'Apex', 'Visualforce'};
        for(Integer i = 0; i < 5; i++){
            Caliber_Category__c cat = new Caliber_Category__c();
            cat.Active__c = true;
            cat.Name = catNames[i];
            cats.add(cat);
        }
        insert cats;
        
        List<String> assessmentTypes = new List<String>{'Exam', 'Verbal', 'Project'};
        List<Caliber_Assessment__c> assessmentList = new List<Caliber_Assessment__c>();
        
        // For each batch, create three assessments for five weeks worth of data.
        for(Training__c batch : batches){
            for(String assessmentType : assessmentTypes){
                for(Integer i = 1; i < 6; i++){
                    Caliber_Assessment__c assessment = new Caliber_Assessment__c();
                    assessment.Assessment_Type__c = assessmentType;
                    assessment.Max_Points__c = 100;
                    assessment.Training_Id__c = batch.Id;
                    assessment.Week_Number__c = i;
                    assessment.Assessment_Category__c = cats[i-1].Id;
                    assessmentList.add(assessment);
                }
            }
        }
        insert assessmentList;
        
        //create grades for assessments
        List<Caliber_Grade__c> grades = new List<Caliber_Grade__c>();
        //iterate through assessments
        for(Integer i = 0; i < 15; i++){
            //iterate through associates
            for(Integer j = 0; j < numAssociates; j++){
                Caliber_Grade__c g = new Caliber_Grade__c();
                g.Caliber_Assessment__c = assessmentList[i].Id;
                g.Contact__c = associates[j].Id;
                g.Score__c = 70 + (2*i);
                grades.add(g);
            }
        }
        insert grades;
        
        // create caliber notes
        List<Caliber_Note__c> qcList = new List<Caliber_Note__c>();
        for(Training__c batch : batches){
            // iterate through weeks
            for (Integer i = 1; i < 6; i++){
                Caliber_Note__c batchQC = new Caliber_Note__c();
                batchQC.Is_QC_Feedback__c = true;
                batchQC.Note_Type__c = 'QC Batch';
                batchQC.QC_Status__c = 'Good';
                batchQC.Training__c = batch.Id;
                batchQC.Week_Number__c = i;
                batchQC.Note_Content__c = 'good job on week ' + i;
                qcList.add(batchQC);
                //iterate through associates
                for (Integer j = 0; j < numAssociates; j++){
                    Caliber_Note__c associateQC = new Caliber_Note__c();
                    associateQC.Contact__c = associates[j].Id;
                    associateQC.Is_QC_Feedback__c = true;
                    associateQC.Note_Type__c = 'QC Trainee';
                    associateQC.QC_Status__c = 'Good';
                    associateQC.Training__c = batch.Id;
                    associateQC.Week_Number__c = i;
                    associateQC.Note_Content__c = 'good job on week ' + i;
                    qcList.add(associateQC);
                }
            }
        }
       insert qcList;
    }
}