src/objects/Caliber_Note__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Caliber Notes</relationshipLabel>
        <relationshipName>Caliber_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training__c</fullName>
        <label>Training</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Caliber Notes</relationshipLabel>
        <relationshipName>Caliber_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Caliber Note</label>
    <nameField>
        <displayFormat>Note-{0000000}</displayFormat>
        <label>Caliber Note Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>Caliber_Number_of_Weeks__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Caliber Number of Weeks</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestQABatchCont.cls
@isTest
public class TestQABatchCont {

    @testSetup
    //Creates Test Data From TestDataFactory Class
    static void createTestData(){
        QATestDataFactory.createTestData(UserInfo.getUserId(), 2 , 10);
    }
    
    @isTest
    static void qaBatchTest(){
        //Test getCurrentBatch() to make sure it doesn't return null
        Training__C aTraining = QABatchTableController.getCurrentBatch();
        System.assertNotEquals(null, aTraining);
        
        //Test getCurrentBatchID to make sure it returns an ID for a Training__c object
        String aTrainingId = QABatchTableController.getCurrentBatchID();
        System.assertNotEquals(null, aTraining);
        //Makes sure returns non-null value
        Training__c returnedTraining = QABatchTableController.incrementWeek(aTraining);
        System.assertNotEquals(null,returnedTraining);
        //Makes sure the methods increments the record from an update
        Training__c updatedTraining = [SELECT id, caliber_number_of_weeks__c,(SELECT id FROM Caliber_Notes__r) FROM Training__c WHERE id = :aTraining.id];
        System.assertEquals(aTraining.Caliber_Number_of_Weeks__c, updatedTraining.Caliber_Number_of_Weeks__c);
        //Makes sure that the method creates new records for the associated caliber_note__c object
        System.assertNotEquals(0,updatedTraining.caliber_notes__r.size());
        
        //Test that the method returns a non-empty list
        List<Training_Assignment__c> taList = QABatchTableController.getAssociates(aTrainingId);
        System.assertNotEquals(0, taList.size());
        
        Contact trainee = new Contact(FirstName='Test', LastName='Trainee');
        insert trainee;
        Contact queriedTrainee = [SELECT id FROM Contact WHERE FirstName = 'Test' AND LastName='Trainee'];
        taList[0].contact__c = queriedTrainee.id;
        update taList;
		//Makes sure that new notes where created for that contact
        Caliber_Note__c aNote = QABatchTableController.getNote(1, queriedTrainee.id);
        System.assertNotEquals(null, aNote);
        //Makes sure no new note was created if it exist
        Integer dmlStatements  = Limits.getDmlStatements();
        Caliber_Note__c validNote = QABatchTableController.getNote(1, queriedTrainee.id);
        System.assertEquals(dmlStatements, Limits.getDmlStatements());
        System.assertNotEquals(null,validNote);
        
        //Makes sure DML statement was successful
        Boolean isSuccessfulDml = true;
        try{
             QABatchTableController.saveNote(validNote);
        }catch(DmlException e){
            isSuccessfulDml = false;
        }
        System.assert(isSuccessfulDml);
    }
    
    /*@isTest
    static void testNotes(){
        Training__C aTraining = QABatchTableController.getCurrentBatch();
        List<Training_Assignment__c> taList = QABatchTableController.getAssociates(aTraining.id);
        Caliber_Note__c aNote = QABatchTableController.getNote(1, taList[0].id);
        System.assertNotEquals(null, aNote);
            
    }*/
}