src/objects/Caliber_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Category</label>
        <referenceTo>Caliber_Category__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <label>Assessment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exam</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Points__c</fullName>
        <description>An arbitrary number designating the maximum number of points a trainee can earn for an assessment. The weighted score (out of 100%) is determined by Caliber_Grade__c.Score__c / Max_Points__c</description>
        <label>Max Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Training_Id__c</fullName>
        <label>Training Id</label>
        <referenceTo>Training__c</referenceTo>
        <relationshipLabel>Caliber Assessments</relationshipLabel>
        <relationshipName>Caliber_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <description>The week that the test was administered, for example a Java Verbal test on Week 1.</description>
        <label>Week Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Caliber Assessment</label>
    <nameField>
        <displayFormat>ASMNT-{0000000}</displayFormat>
        <label>Caliber Assessment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Caliber Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Training__c.object
<CustomObject>
    <fields>
        <fullName>Caliber_Number_of_Weeks__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Caliber Number of Weeks</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training</label>
    <nameField>
        <displayFormat>TRNG-{00000000}</displayFormat>
        <label>Training ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CategoriesCoveredControllerTest.cls
@isTest
public class CategoriesCoveredControllerTest {
    @isTest
    public static void testGetCategories()
    {
        //create one training
        Training__c training = new Training__c(Caliber_Number_Of_Weeks__c=1);
        insert training;
        //insert two caliber categories with different names
        Caliber_Category__c soql = new Caliber_Category__c(Name='SOQL');
        Caliber_Category__c sosl = new Caliber_Category__c(Name='SOSL');
        insert soql;
        insert sosl;
        //create one caliber assessment
        Caliber_Assessment__c caliber_assessment_soql = new Caliber_Assessment__c(Training_Id__c=training.Id, Week_Number__c=1, Max_Points__c=50, Assessment_Type__c='Verbal', Assessment_Category__c=soql.Id);
        Caliber_Assessment__c caliber_assessment_sosl = new Caliber_Assessment__c(Training_Id__c=training.Id, Week_Number__c=1, Max_Points__c=50, Assessment_Type__c='Verbal', Assessment_Category__c=sosl.Id);
        insert caliber_assessment_soql;
        insert caliber_assessment_sosl;
        //Call the apex function.
        String result = QACategoriesCoveredController.getCategories(training.Id, 1);
        //Assert that the resulting string was created and returned successfully.
        System.assertEquals('SOQL, SOSL', result);
        String result2 = QACategoriesCoveredController.getCategories(null, 1);
        //Assert that the resulting string was created and returned successfully.
        System.assertEquals('', result2);
    }
}